version: "3.3"

services:

  db:
    build:
      context: .
      dockerfile: ./dockerfile/postgresql/Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
      - .init.sql:/docker-entrypoint-initdb/10-init.sql
    restart: on-failure:10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - ./environment/dev/project.env

  django:
    build:
      context: .
      dockerfile: ./dockerfile/django/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/code/
    env_file:
      - ./environment/dev/project.env
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  db-data:


