# Generated by Django 3.0.6 on 2020-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countries',
            field=models.ManyToManyField(related_name='profiles', through='app.ChosenCountry', to='app.Country'),
        ),
    ]
