# Generated by Django 3.0.6 on 2020-05-31 00:43

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200530_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.CreateModel(
            name='Chosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.IntegerField(choices=[(1, '%H:%M:%S'), (2, '%l:%M:%p'), (3, '%r'), (4, '%R'), (5, '%T')], default=1)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Lisbon')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='app.Profile')),
            ],
        ),
    ]
